<?xml version="1.0" ?>
<robot name="$(arg robotName)" xmlns:xacro="http://ros.org/wiki/xacro">

<!-- #### constants #### -->
<xacro:property name="deg_to_rad" value="0.017453"/>
<xacro:property name="PI" value="3.14"/>

<xacro:macro name="cylinder_inertia" params ="m r h"> 
    <inertial> 
        <mass value="${m}"/> 
        <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0.0" ixz="0.0" 
                 iyy="${m*(3*r*r+h*h)/12}" iyz= "0.0" 
                 izz="${m*r*r/2}"/> 
     </inertial> 
 </xacro:macro>

<!-- #### body property #### -->
<xacro:property name="body_length" value=".45"/>
<xacro:property name="body_width" value=".45"/>
<xacro:property name="body_height" value=".45"/>

<!-- ####  leg property #### -->
<xacro:property name="leg_radius" value="0.025"/>
<xacro:property name="leg_length" value="0.32"/>
<xacro:property name="leg_mass" value="1"/>

<!-- #####  leg macro  ##### -->
<xacro:macro name="leg" params= "prefix suffix X1 X2 Y1 Y2">
           
  <joint name="${prefix}_${suffix}_leg_joint" type="fixed">
    <parent link= "body"/>
    <child link= "${prefix}_${suffix}_leg"/>
    <origin xyz= "${(body_length/2)*X1 + (body_length/2)*X2} ${(body_width/2)*Y1 + (body_width/2)*Y2}  ${leg_length/2}" rpy="0 0 0"/>
    <dynamics damping="0.0" friction="0.0"/>  
  </joint>

  <link name= "${prefix}_${suffix}_leg">
    <!--
    <visual>
      <origin rpy= "0 0 0" xyz= "0 0 0"/>
      <geometry>   
        <cylinder length="${leg_length}" radius= "${leg_radius}"/>
      </geometry>
      <material name= "light_black"/>
    </visual>
-->`
    <collision>
      <origin rpy= "0 0 0" xyz= "0 0 0"/>
      <geometry>
        <cylinder length="${leg_length}" radius= "${leg_radius}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="${leg_mass}" r="${leg_radius}" h="${leg_length}"/>
  </link>
         
     
  <gazebo reference ="${prefix}_${suffix}_leg">
    <mu1 value=".005"/>
    <mu2 value=".005"/>
    <kp value="10000000.0"/>
    <kd value= "10.0"/>
    <maxVel>0.</maxVel>
    <minDepth>0.001</minDepth>
  </gazebo>
                 
</xacro:macro>

  <!-- body-->
  <link name="body">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://amr_description/meshes/only_shelf.stl" scale="0.01 0.01 0.01"/>
      </geometry>
    </visual>

    <collision>
       <origin rpy="0 0 0" xyz="0 0 ${leg_length + body_height/2}"/>
       <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
       </geometry>
     </collision>
     <inertial>
         <mass value="1.0"/>
              <inertia ixx="1.3542" ixy="0.0"
                       iyy="1.3542" iyz="0.0"
                       izz="1.3542" ixz="0.0"/>
    </inertial>
   </link>

  <gazebo reference="body">
      <material>Gazebo/CeilingTiled</material>
  </gazebo>

<!-- #### 4 legs #### -->
  <xacro:leg prefix="right" suffix="front" X1="0" X2="1" Y1="-1" Y2="0" />
  <xacro:leg prefix="right" suffix="back" X1="-1" X2="0" Y1="-1" Y2="0"/>
  <xacro:leg prefix="left" suffix="front" X1="0" X2="1" Y1="0" Y2="1"/>
  <xacro:leg prefix="left" suffix="back" X1="-1" X2="0" Y1="0" Y2="1"/>


<!-- #### B bottom #### -->
  <joint name="B_bot_joint" type="fixed">
    <parent link="body"/>
    <child link="B_bot" />
    <origin xyz="0 0 ${leg_length} " rpy="0 0 0"/>
  </joint>

  <link name="B_bot">
    <visual>
      <origin xyz="0.0 0 0.0" rpy="${PI} 0 ${PI/2}"/>
      <geometry>
        <!--
        <mesh filename="package://amr_description/meshes/B_bot.stl" scale="0.01 0.01 0.01"/>
-->
        <mesh filename="package://amr_description/meshes/B_bot_shrink10mm.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <max_contacts>1</max_contacts>
      <origin xyz="0.0 0 0.0" rpy="${PI} 0 ${PI/2}"/>
      <geometry>
        <!--
        <mesh filename="package://amr_description/meshes/B_bot.stl" scale="0.01 0.01 0.01"/>
-->
        <mesh filename="package://amr_description/meshes/B_bot_shrink10mm.stl" scale="0.01 0.01 0.01"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.5"/>
      <inertia ixx="2.15625e-02" ixy="0" ixz="0"
               iyy="2.15625e-02" iyz="0"
               izz="2.25e-02" />
    </inertial>
  </link>

  <gazebo reference="B_bot">
      <mu1>0</mu1>
      <mu2>0</mu2>
      <kp>1000000</kp> 
      <kd>10</kd>
      <maxVel>0.</maxVel>
      <minDepth>0.001</minDepth>
      <material>Gazebo/Wood</material>
  </gazebo>


</robot>
