<?xml version="1.0" ?>
<robot name="$(arg robotName)" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find amr_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find amr_description)/urdf/solamr.gazebo.xacro"/>

  <xacro:property name="r200_cam_rgb_px" value="0.005"/>
  <xacro:property name="r200_cam_rgb_py" value="0.018"/>
  <xacro:property name="r200_cam_rgb_pz" value="0.013"/>
  <xacro:property name="r200_cam_depth_offset" value="0.01"/>

    <!-- #### constants #### -->
    <xacro:property name="deg_to_rad" value="0.017453"/>
    <xacro:property name="PI" value="3.14"/>

    <xacro:macro name="cylinder_inertia" params ="m r h"> 
        <inertial> 
            <mass value="${m}"/> 
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0.0" ixz="0.0" 
                     iyy="${m*(3*r*r+h*h)/12}" iyz= "0.0" 
                     izz="${m*r*r/2}"/> 
         </inertial> 
     </xacro:macro>

    <!-- #### chassis property #### -->
    <xacro:property name="chassis_length" value=".65"/>
    <xacro:property name="chassis_width" value=".3"/>
    <xacro:property name="chassis_height" value="0.05"/>

    <!-- ####  caster property #### -->
    <xacro:property name="caster_radius" value="0.025"/>
    <xacro:property name="caster_length" value="0.015"/>
    <xacro:property name="caster_mass" value=".2"/>


    <!-- #####  caster macro  ##### -->

    <xacro:macro name="caster" params= "prefix suffix X1 X2 Y1 Y2">
                     
      <joint name="${prefix}_${suffix}_caster_joint" type="fixed">
        <parent link= "chassis"/>
        <child link= "${prefix}_${suffix}_caster"/>
        <origin xyz= "${(chassis_length/2)*X1 + (chassis_length/2-.05)*X2} ${(chassis_width/2-0.02)*Y1 + (chassis_width/2)*Y2}  ${caster_radius + 0.01}" rpy="0 0 0"/>
        <dynamics damping="0.0" friction="0.0"/>  
      </joint>
               
      <link name= "${prefix}_${suffix}_caster">
        <visual>
          <origin rpy= "${PI/2} 0 0" xyz= "0 0 -0.025"/>
          <geometry>
              <mesh filename="package://amr_description/meshes/solamr/caster.stl" scale="0.0002 0.0002 0.0002"/>
          </geometry>
          <material name= "grey"/>
        </visual>
        <collision>
          <origin rpy= "${PI/2} 0 0" xyz= "0 0 0"/>
          <geometry>
            <cylinder length="${caster_length}" radius= "${caster_radius}"/>
          </geometry>
        </collision>
        <xacro:cylinder_inertia m="${caster_mass}" r="${caster_radius}" h="${caster_length}"/>
      </link>
             
         
      <gazebo reference ="${prefix}_${suffix}_caster">
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
        <kp value="10000000.0"/>
        <kd value= "1.0"/>
        <material>Gazebo/WhiteGlow</material>
      </gazebo>
    </xacro:macro>

  <link name="base_footprint"/>

<!-- #####   BEGIN  ##### -->
<!-- #####  A1 PART ##### -->
<!-- #####   BEGIN  ##### -->

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="chassis" />
    <origin xyz="0 0 0.0" rpy="0 0 0"/>
  </joint>

  <link name="chassis">
    <visual>
      <origin xyz="0.0 0 0.075" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <collision>
      <origin xyz="0.0 0 0.075" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="15"/>
      <inertia ixx="1.15625e-01" ixy="0" ixz="0"
               iyy="1.15625e-01" iyz="0"
               izz="2.25e-01" />
    </inertial>
  </link>

  <joint name="wheel_left_joint" type="continuous">
    <parent link="chassis"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.0 ${chassis_width/2-0.05} 0.025" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
          <mesh filename="package://amr_description/meshes/solamr/left_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="chassis"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.0 -${chassis_width/2-0.05} 0.025" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
          <mesh filename="package://amr_description/meshes/solamr/right_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

<!-- #### 4 casters #### -->
  <xacro:caster prefix="right" suffix="front" X1="0" X2="1" Y1="-1" Y2="0" />
  <xacro:caster prefix="right" suffix="back" X1="-1" X2="0" Y1="-1" Y2="0"/>
  <xacro:caster prefix="left" suffix="front" X1="0" X2="1" Y1="0" Y2="1"/>
  <xacro:caster prefix="left" suffix="back" X1="-1" X2="0" Y1="0" Y2="1"/>

<!-- #### Sensors : Lidar #### -->

  <joint name="scan_joint1" type="fixed">
    <parent link="chassis"/>
    <child link="scan_front"/>
    <origin xyz="${chassis_length/2-0.03} ${chassis_width/2-0.03} 0.16" rpy="0 0 -${PI/2}"/>
  </joint>

  <link name="scan_front">
    <visual>
      <origin xyz="0 0 -.06" rpy="${PI/2} 0 0"/>
      <geometry>
        <mesh filename="package://amr_description/meshes/sensors/hokuyo_lidar.stl" scale="0.012 0.012 0.012"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 -.03" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.08" radius="0.025"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="scan_joint2" type="fixed">
    <parent link="chassis"/>
    <child link="scan_rear"/>
    <origin xyz="-${chassis_length/2-0.03} -${chassis_width/2-0.03} 0.16" rpy="0 0 ${PI/2}"/>
  </joint>

  <link name="scan_rear">
    <visual>
      <origin xyz="0 0 -.06" rpy="${PI/2} 0 0"/>
      <geometry>
        <mesh filename="package://amr_description/meshes/sensors/hokuyo_lidar.stl" scale="0.012 0.012 0.012"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <collision>
      <origin xyz="0 0 -0.03" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.08" radius="0.025"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

<!-- #####    END   ##### -->
<!-- #####  A1 PART ##### -->
<!-- #####    END   ##### -->
<!--
<gazebo>
  <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
    <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
  </plugin>
</gazebo>
-->


<!-- #####   BEGIN  ##### -->
<!-- #####  A2 PART ##### -->
<!-- #####   BEGIN  ##### -->

  <joint name="A2_top_joint" type="fixed">
    <parent link="chassis"/>
    <child link="A2_top" />
    <origin xyz="0 0 0.18" rpy="0 0 0"/>
  </joint>

  <link name="A2_top">
    <visual>
      <origin xyz="0.0 0 0.0" rpy="0 0 -${PI/2}"/>
      <geometry>
        <mesh filename="package://amr_description/meshes/solamr/A2_top_H.stl" scale="0.01 0.01 0.01"/>
        <!--
        <mesh filename="package://amr_description/meshes/solamr/A2_top_extr10mm_H.stl" scale="0.01 0.01 0.01"/>
-->
      </geometry>
      <material name="white"/>
    </visual>

    <collision>
      <max_contacts>1</max_contacts>
      <origin xyz="0.0 0 0.0" rpy="0 0 -${PI/2}"/>
      <geometry>
        <mesh filename="package://amr_description/meshes/solamr/A2_top_H.stl" scale="0.01 0.01 0.01"/>
        <!--
        <mesh filename="package://amr_description/meshes/solamr/A2_top_extr10mm_H.stl" scale="0.01 0.01 0.01"/>
-->
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.5"/>
      <inertia ixx="2.15625e-02" ixy="0" ixz="0"
               iyy="2.15625e-02" iyz="0"
               izz="2.25e-02" />
    </inertial>
  </link>

  <transmission name="blocker_tran" type="SimpleTransmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="blocker_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="blocker_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>500</mechanicalReduction>
    </actuator>
  </transmission>

  <joint name="blocker_joint" type="continuous">
    <parent link="chassis"/>
    <child link="blocker"/>
    <origin xyz="0.077 0 .2" rpy="0 1.57 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="blocker">
    <visual>
      <!--
      <origin xyz=".02 0 -0.0095" rpy="0 0 0"/>
-->
      <origin xyz=".015 0 -0.002" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://amr_description/meshes/solamr/blocker.stl" scale="0.009 0.009 0.009"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <collision>
      <max_contacts>1</max_contacts>
      <origin xyz=".02 0 -0.00" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://amr_description/meshes/solamr/blocker.stl" scale="0.009 0.009 0.009"/>
      </geometry>
    </collision>

    <gazebo reference ="blocker">
      <material>Gazebo/Orange</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo> 

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="6.721e-04" ixy="0" ixz="0"
               iyy="6.721e-04" iyz="0"
               izz="1.3141e-03" />
    </inertial>
  </link>




<!-- #####    END   ##### -->
<!-- #####  A2 PART ##### -->
<!-- #####    END   ##### -->


<!-- Begin of camera -->

  <joint name="camera_joint" type="fixed">
    <origin xyz="0.33 0 0.161" rpy="0 -0.35 0"/>
    <parent link="chassis"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <visual>
     <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
      <geometry>
          <mesh filename="package://amr_description/meshes/sensors/r200.dae" />
      </geometry>
    </visual>
    <!--
    <collision>
      <origin xyz="0.003 0.065 0.007" rpy="0 0 0"/>
      <geometry>
        <box size="0.012 0.132 0.020"/>
      </geometry>
    </collision>
-->
  </link>

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <link name="camera_rgb_optical_frame"/>

  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_depth_frame"/>
  </joint>
  <link name="camera_depth_frame"/>

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_depth_frame"/>
    <child link="camera_depth_optical_frame"/>
  </joint>
  <link name="camera_depth_optical_frame"/>

<!-- End of camera -->

</robot>
