    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    # Position Controllers ---------------------------------------
    blocker_position_controller:
        type: effort_controllers/JointPositionController
        joint: blocker_joint
        pid: {p: 100.0, i: 0.0, d: 1.0}
